name: charset_converter
description: Charset/encoding converter that uses underlying platform - no external dependencies
version: 2.0.0
homepage: https://github.com/pr0gramista/charset_converter
repository: https://github.com/pr0gramista/charset_converter

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  # Flutter versions prior to 1.10 did not support the flutter.plugin.platforms map.
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: pl.pr0gramista.charset_converter
        pluginClass: CharsetConverterPlugin
      ios:
        pluginClass: CharsetConverterPlugin
